name: mae-mimic-cxr
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.9.*
  - timm=0.4.12
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - cudatoolkit=11.6
  - jupyter
  - pandas